name: model_generator_example
description: A project used to demo the model generator
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  model_generator:
    path: ../

dependency_overrides:
  path: 1.7.0 #Because model_generator >=1.2.0 depends on path ^1.7.0 and every version of flutter_test from sdk depends on path 1.6.4, model_generator >=1.2.0 is incompatible with flutter_test from sdk.

#This is the default config
#In the model_generator/config.yaml you will see a object with a custom base_directory
#
model_generator:
  config_path: model_generator/config.yaml
#  nullsafety: true
#  base_directory: model